apiVersion: config.mas.ibm.com/v1
kind: JdbcCfg
metadata:
  name: {{ .Values.database.jdbcname }}
  labels:
    {{- include "ibm-mas-jdbc.scopelabels" . | nindent 4 }}
    {{- include "ibm-mas-jdbc.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  config:
    credentials:
      secretName: {{ .Values.database.secretname }}
    sslEnabled: true
    url: {{ .Values.database.url | quote }}
  
  displayName: {{ .Values.database.url | quote }}
  type: external
  certificates: 
    - alias: {{ .Values.masapp.appid | quote }}
      crt: |-
{{ .Values.database.dbcert | nindent 8 }}
